import type { Metadata } from 'next';
import { PublicShell } from '@/components/public/PublicShell';

export const metadata: Metadata = { title: 'Terms | CaliforniaMailer', description: 'Draft website and campaign terms for CaliforniaMailer.', alternates: { canonical: 'https://californiamailer.com/terms' } };

export default function TermsPage() {
  return <PublicShell><article className="mx-auto max-w-4xl px-5 py-20"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-bold text-amber-950">Draft website terms. Payment remains disabled until final business identity, address, campaign contract, and legal review are complete.</div><h1 className="mt-8 text-4xl font-black tracking-tight md:text-6xl">Terms</h1><Term title="Website information">Public campaign information is provided for review. A target, proposal, estimate, hold, or configuration preview is not a delivery guarantee, paid reservation, or representation of business results.</Term><Term title="Campaign contract">If payments activate, the named campaign terms, placement, price, deadline, refund policy, content standards, proof procedure, and checkout record form the campaign agreement. Conflicting general copy does not expand the purchased scope.</Term><Term title="No performance promise">CaliforniaMailer does not promise response, calls, leads, appointments, sales, profit, or return on investment.</Term><Term title="Advertiser responsibility">Advertisers must own or license submitted materials and substantiate claims, prices, licenses, and required disclaimers. Final written approval confirms the advertiser reviewed the exact proof.</Term><Term title="Funding and printing">Only cleared net funding counts. Printing requires the separate readiness gate and manual owner authorization described in the funding policy.</Term><Term title="Availability">Category and placement availability can change only through real holds, cleared payments, expiration, cancellation, refund, or an explicitly recorded owner exception.</Term><Term title="Questions">Contact hello@californiamailer.com before relying on a campaign term that is unclear.</Term></article></PublicShell>;
}

function Term({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-10"><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 leading-8 text-slate-700">{children}</p></section>; }
