import type { Metadata } from 'next';
import Link from 'next/link';
import { PublicShell } from '@/components/public/PublicShell';
import { FOUNDING_CAMPAIGN } from '@/config/foundingCampaign';

export const metadata: Metadata = { title: 'Draft Terms | CaliforniaMailer', description: 'Draft website and campaign terms for owner and legal review.', alternates: { canonical: 'https://californiamailer.com/terms' }, robots: { index: false, follow: false } };

export default function TermsPage() {
  return <PublicShell><article className="mx-auto max-w-4xl px-5 py-20"><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm font-bold text-amber-950">Draft terms version {FOUNDING_CAMPAIGN.termsVersion}. Payment remains disabled until final business identity, address, complete versioned campaign contract, and legal review are complete.</div><h1 className="mt-8 text-4xl font-black tracking-tight md:text-6xl">Draft terms</h1><Term title="Website information">Public campaign information is provided for review. A target, proposal, estimate, inquiry, or configuration preview is not a delivery guarantee, paid reservation, or representation of business results.</Term><Term title="Future campaign contract">No campaign contract is approved for checkout. If payments activate later, the owner-approved, versioned campaign terms, placement, price, deadline, refund policy, content standards, proof requirements, and checkout record must identify the complete agreement before acceptance.</Term><Term title="No performance promise">CaliforniaMailer does not promise response, calls, leads, appointments, sales, profit, or return on investment.</Term><Term title="Advertiser responsibility">Advertisers must own or license submitted materials and substantiate claims, prices, licenses, and required disclaimers. Final written approval would apply only to the exact numbered proof.</Term><Term title="Funding and printing">No funding term is active. Any future cleared net funding would still require a separate production-readiness gate and manual owner authorization before printing.</Term><Term title="Availability">No category or placement is offered while these terms remain draft. Any future availability rule must appear in an approved campaign contract and be backed by actual records; an inquiry creates no hold or exclusivity.</Term><Term title="Questions">Use the <Link href="/contact" className="font-bold text-blue-700 underline">contact page</Link> for the current inquiry boundary. Do not rely on a draft campaign term.</Term></article></PublicShell>;
}

function Term({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-10"><h2 className="text-2xl font-black">{title}</h2><p className="mt-3 leading-8 text-slate-700">{children}</p></section>; }
