import type { Metadata } from 'next';
import { PublicShell } from '@/components/public/PublicShell';

export const metadata: Metadata = { title: 'Advertiser Content Standards | CaliforniaMailer', description: 'Claims, categories, rights, and review standards for shared-mailer advertising.', alternates: { canonical: 'https://californiamailer.com/advertiser-content-standards' } };

const rejected = ['False or misleading claims or prices', 'Illegal services or goods', 'Adult sexual services', 'Weapons', 'Tobacco or nicotine', 'Recreational drugs', 'Counterfeit goods', 'Hate or extremist content', 'Deceptive financial claims', 'Unlicensed professional claims', 'Unsupported medical claims', 'Guaranteed outcomes', 'Copyright-infringing images', 'Trademark misuse'];

export default function ContentStandardsPage() {
  return <PublicShell><article className="mx-auto max-w-4xl px-5 py-20"><h1 className="text-4xl font-black tracking-tight md:text-6xl">Advertiser content standards</h1><p className="mt-5 text-lg leading-8 text-slate-700">Every advertiser is responsible for the accuracy, rights, licenses, prices, terms, and disclaimers in its placement. CaliforniaMailer may reject or pause content that is unsafe, unlawful, unsupported, or unsuitable for a household mailer.</p><h2 className="mt-12 text-2xl font-black">Rejected or flagged content</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{rejected.map((item) => <li key={item} className="rounded-xl border border-slate-200 px-4 py-3">{item}</li>)}</ul><h2 className="mt-12 text-2xl font-black">Manual review categories</h2><p className="mt-4 leading-8 text-slate-700">Health, dental, legal, financial, real-estate, licensed professional, age-restricted, and other sensitive claims require owner review and appropriate evidence or disclaimers before payment or publication. CaliforniaMailer does not verify professional advice for the advertiser.</p><h2 className="mt-12 text-2xl font-black">Proof approval</h2><p className="mt-4 leading-8 text-slate-700">The advertiser must approve the exact final version in writing. A later content change invalidates that approval and requires a new version decision.</p></article></PublicShell>;
}
