'use client';

import { useState } from 'react';

export function DealsConsentForm({ mode = 'signup' }: { mode?: 'signup' | 'unsubscribe' }) {
  const [email, setEmail] = useState(''); const [consent, setConsent] = useState(false); const [code, setCode] = useState(''); const [phase, setPhase] = useState<'request' | 'confirm' | 'done'>('request'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function requestCode(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const response = await fetch('/api/subscribers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: mode === 'signup' ? 'request_signup' : 'request_unsubscribe', email, ...(mode === 'signup' ? { consent, source: 'monterey_deals_page' } : {}), website: '' }) }); const data = await response.json(); setMessage(data.message || data.error); if (response.ok) setPhase('confirm'); setBusy(false); }
  async function confirm(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const response = await fetch('/api/subscribers', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: mode === 'signup' ? 'confirm_signup' : 'confirm_unsubscribe', email, code }) }); const data = await response.json(); setMessage(response.ok ? (mode === 'signup' ? 'Email verified. You are subscribed.' : 'Unsubscribe confirmed and suppression recorded.') : data.error); if (response.ok) setPhase('done'); setBusy(false); }
  if (phase === 'done') return <p className="rounded-xl bg-emerald-50 p-5 font-bold text-emerald-900">{message}</p>;
  if (phase === 'confirm') return <form onSubmit={confirm} className="space-y-4"><p className="text-sm text-slate-600">{message}</p><label className="block text-sm font-bold">Six-digit email code<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} className="mt-1 w-full rounded-lg border px-3 py-3 font-normal" /></label><button disabled={busy} className="rounded-lg bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-50">Confirm {mode === 'signup' ? 'signup' : 'unsubscribe'}</button></form>;
  return <form onSubmit={requestCode} className="space-y-4"><label className="block text-sm font-bold">Email address<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-3 font-normal" /></label>{mode === 'signup' && <label className="flex items-start gap-3 rounded-lg border p-4 text-sm leading-6"><input required type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-1" />Yes, email me Monterey Peninsula offers no more than twice per month. I understand I can unsubscribe at any time. This box is not preselected.</label>}<button disabled={busy || (mode === 'signup' && !consent)} className="rounded-lg bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-40">{busy ? 'Requesting…' : mode === 'signup' ? 'Email me a verification code' : 'Email me an unsubscribe code'}</button>{message && <p className="text-sm font-bold text-rose-800">{message}</p>}</form>;
}
