'use client';

import Sidebar from '@/components/Sidebar';
import { useAuth } from '@/lib/AuthContext';
import { useCallback, useEffect, useState } from 'react';

interface Reservation { id: string; businessName: string; categorySlug: string; status: string; materialsStatus: string }
interface Proof { id: string; reservationId: string; businessName: string; version: number; status: string; originalName: string; revisionRequests: Array<{ text?: string }>; approvedAt: string | null; approvedBy: string | null }
interface Material { id: string; reservationId: string; originalName: string; kind: string; status: string }

export default function ProofWorkflowPage() {
  const { user, loading, logout } = useAuth(); const [reservations, setReservations] = useState<Reservation[]>([]); const [proofs, setProofs] = useState<Proof[]>([]); const [materials, setMaterials] = useState<Material[]>([]); const [reservationId, setReservationId] = useState(''); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const authFetch = useCallback(async (url: string, init: RequestInit = {}) => {
    if (!user) throw new Error('Owner access required.'); const headers = new Headers(init.headers); headers.set('Authorization', `Bearer ${await user.getIdToken()}`); const response = await fetch(url, { ...init, headers }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Proof request failed.'); return data;
  }, [user]);
  const load = useCallback(async () => { const data = await authFetch('/api/admin/proofs'); setReservations(data.reservations); setProofs(data.proofs.sort((a: Proof, b: Proof) => b.version - a.version)); setMaterials(data.materials); }, [authFetch]);
  useEffect(() => { if (user) void load().catch((caught) => setMessage(caught instanceof Error ? caught.message : 'Proof data unavailable.')); }, [load, user]);
  async function upload(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); form.set('reservationId', reservationId); form.set('notes', notes);
    try { const result = await authFetch('/api/admin/proofs', { method: 'POST', body: form }); setMessage(`Private proof version ${result.version} created. No approval is inferred.`); event.currentTarget.reset(); setNotes(''); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'Proof upload failed.'); } finally { setBusy(false); }
  }
  async function reviewMaterial(id: string, action: 'approve' | 'reject') {
    setBusy(true); setMessage(''); try { await authFetch(`/api/admin/materials/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action }) }); setMessage(`Material ${action === 'approve' ? 'approved for private production use' : 'rejected'}. It was not made public.`); await load(); } catch (caught) { setMessage(caught instanceof Error ? caught.message : 'Material review failed.'); } finally { setBusy(false); }
  }
  if (loading) return <Centered>Loading owner access…</Centered>; if (!user) return <Centered>Sign in with the owner account.</Centered>;
  const paid = reservations.filter((item) => item.status === 'paid');
  return <div className="min-h-screen bg-slate-50 md:flex"><Sidebar /><main className="min-w-0 flex-1 p-4 md:p-8"><header className="mb-7 flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Private production</p><h1 className="text-3xl font-black">Materials and proof workflow</h1></div><button onClick={logout} className="rounded-lg border px-3 py-2 text-sm">Sign out</button></header><div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950">Files remain private. Advertiser uploads enter quarantine pending owner review. Proofs are versioned; only the latest exact version can receive a written decision. A file upload, view, or prior-version approval never satisfies the print gate.</div>{message && <p className="mb-5 rounded-lg bg-blue-50 p-3 text-sm font-bold text-blue-900">{message}</p>}
    <section className="grid gap-6 xl:grid-cols-[400px_1fr]"><form onSubmit={upload} className="rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Issue numbered proof</h2><label className="mt-4 block text-sm font-bold">Paid reservation<select required value={reservationId} onChange={(event) => setReservationId(event.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal"><option value="">Select…</option>{paid.map((item) => <option key={item.id} value={item.id}>{item.businessName} · {item.categorySlug}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Private proof file<input required name="file" type="file" accept="image/png,image/jpeg,application/pdf" className="mt-2 block w-full text-sm" /></label><label className="mt-4 block text-sm font-bold">Owner note<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={4} className="mt-1 w-full rounded-lg border px-3 py-2 font-normal" /></label><button disabled={busy || !reservationId} className="mt-5 w-full rounded-lg bg-blue-700 px-5 py-3 font-black text-white disabled:opacity-40">{busy ? 'Working…' : 'Store and issue proof'}</button>{paid.length === 0 && <p className="mt-4 text-sm text-slate-500">No paid reservations. The workflow will not accept an interest, hold, or pending payment.</p>}</form>
      <div className="rounded-xl border bg-white shadow-sm"><h2 className="border-b p-5 text-xl font-black">Proof ledger</h2>{proofs.length ? <ul className="divide-y">{proofs.map((proof) => <li key={proof.id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{proof.businessName} · version {proof.version}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">{proof.status.replaceAll('_', ' ')}</span></div><a href={`/api/admin/proofs/${proof.id}/file`} target="_blank" rel="noreferrer" className="mt-2 inline-block font-bold text-blue-700 underline">Open private {proof.originalName}</a>{proof.revisionRequests.length > 0 && <p className="mt-2 text-sm text-amber-800">Latest revision: {proof.revisionRequests.at(-1)?.text || 'See record'}</p>}{proof.approvedAt && <p className="mt-2 text-xs text-slate-500">Approved by {proof.approvedBy} at {new Date(proof.approvedAt).toLocaleString()}</p>}</li>)}</ul> : <p className="p-8 text-center text-sm text-slate-500">No real proof records.</p>}</div></section>
    <section className="mt-7 rounded-xl border bg-white shadow-sm"><h2 className="border-b p-5 text-xl font-black">Quarantined advertiser materials</h2>{materials.length ? <ul className="divide-y">{materials.map((item) => <li key={item.id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><strong>{reservations.find((reservation) => reservation.id === item.reservationId)?.businessName || item.reservationId}</strong><p className="text-sm text-slate-500">{item.originalName} · {item.status.replaceAll('_', ' ')}</p></div><div className="flex gap-2"><a href={`/api/admin/materials/${item.id}/file`} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-sm font-bold">Download privately</a>{item.status === 'quarantine_pending_owner_review' && <><button disabled={busy} onClick={() => void reviewMaterial(item.id, 'approve')} className="rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white">Approve private use</button><button disabled={busy} onClick={() => void reviewMaterial(item.id, 'reject')} className="rounded-lg border border-rose-300 px-3 py-2 text-sm font-bold text-rose-800">Reject</button></>}</div></li>)}</ul> : <p className="p-8 text-center text-sm text-slate-500">No uploaded materials.</p>}</section>
  </main></div>;
}
function Centered({ children }: { children: React.ReactNode }) { return <div className="flex min-h-screen items-center justify-center p-8 text-center text-slate-600">{children}</div>; }
